[2023-05-11T06:19:14.427+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mongodb_backup.run_script scheduled__2023-05-11T05:40:00+00:00 [queued]>
[2023-05-11T06:19:14.439+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mongodb_backup.run_script scheduled__2023-05-11T05:40:00+00:00 [queued]>
[2023-05-11T06:19:14.440+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-11T06:19:14.452+0000] {taskinstance.py:1350} INFO - Executing <Task(SSHOperator): run_script> on 2023-05-11 05:40:00+00:00
[2023-05-11T06:19:14.459+0000] {standard_task_runner.py:57} INFO - Started process 3281 to run task
[2023-05-11T06:19:14.474+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Mongodb_backup', 'run_script', 'scheduled__2023-05-11T05:40:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/dagforbackup.py', '--cfg-path', '/tmp/tmptaqzyakw']
[2023-05-11T06:19:14.477+0000] {standard_task_runner.py:85} INFO - Job 193: Subtask run_script
[2023-05-11T06:19:14.539+0000] {task_command.py:410} INFO - Running <TaskInstance: Mongodb_backup.run_script scheduled__2023-05-11T05:40:00+00:00 [running]> on host b06a232a05e5
[2023-05-11T06:19:14.628+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Mongodb_backup' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2023-05-11T05:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-11T05:40:00+00:00'
[2023-05-11T06:19:14.629+0000] {ssh.py:135} INFO - Creating ssh_client
[2023-05-11T06:19:14.683+0000] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2023-05-11T06:19:14.696+0000] {base.py:73} INFO - Using connection ID 'ssh_conn' for task execution.
[2023-05-11T06:19:14.763+0000] {ssh.py:299} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-05-11T06:19:15.325+0000] {transport.py:1873} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2023-05-11T06:19:16.460+0000] {transport.py:1873} INFO - Authentication (publickey) successful!
[2023-05-11T06:19:16.466+0000] {ssh.py:476} INFO - Running command: 
echo 'Running shell script'
whoami
sh -x /home/ubuntu/dbbackup.sh
[2023-05-11T06:19:17.288+0000] {ssh.py:522} INFO - Running shell script
[2023-05-11T06:19:17.293+0000] {ssh.py:522} INFO - ubuntu
[2023-05-11T06:19:17.295+0000] {ssh.py:522} INFO - total 4.0K
[2023-05-11T06:19:17.296+0000] {ssh.py:522} INFO - -rw-r--r-- 1 ubuntu ubuntu 166 May 11 06:19 dbbackup.sh
[2023-05-11T06:19:17.298+0000] {ssh.py:527} WARNING - + cd /home/ubuntu
[2023-05-11T06:19:17.299+0000] {ssh.py:527} WARNING - + ls -lthr
[2023-05-11T06:19:17.300+0000] {ssh.py:527} WARNING - + date +%Y-%m-%d.gz
[2023-05-11T06:19:17.556+0000] {ssh.py:527} WARNING - + mongodump --forceTableScan --db led --gzip --archive=mongoBackup_2023-05-11.gz
[2023-05-11T06:19:17.557+0000] {ssh.py:527} WARNING - /home/ubuntu/dbbackup.sh: 6: mongodump: not found
[2023-05-11T06:19:17.557+0000] {ssh.py:527} WARNING - + ls -lthr
[2023-05-11T06:19:17.558+0000] {ssh.py:522} INFO - total 4.0K
[2023-05-11T06:19:17.559+0000] {ssh.py:522} INFO - -rw-r--r-- 1 ubuntu ubuntu 166 May 11 06:19 dbbackup.sh
[2023-05-11T06:19:17.619+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=Mongodb_backup, task_id=run_script, execution_date=20230511T054000, start_date=20230511T061914, end_date=20230511T061917
[2023-05-11T06:19:17.680+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-11T06:19:17.714+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
