[2023-05-11T04:33:09.011+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mongodb_backup.test_ssh_operator scheduled__2023-05-11T04:20:00+00:00 [queued]>
[2023-05-11T04:33:09.019+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mongodb_backup.test_ssh_operator scheduled__2023-05-11T04:20:00+00:00 [queued]>
[2023-05-11T04:33:09.020+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 3
[2023-05-11T04:33:09.031+0000] {taskinstance.py:1350} INFO - Executing <Task(SSHOperator): test_ssh_operator> on 2023-05-11 04:20:00+00:00
[2023-05-11T04:33:09.036+0000] {standard_task_runner.py:57} INFO - Started process 1028 to run task
[2023-05-11T04:33:09.041+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Mongodb_backup', 'test_ssh_operator', 'scheduled__2023-05-11T04:20:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/dagforbackup.py', '--cfg-path', '/tmp/tmpzswt2w_u']
[2023-05-11T04:33:09.042+0000] {standard_task_runner.py:85} INFO - Job 103: Subtask test_ssh_operator
[2023-05-11T04:33:09.103+0000] {task_command.py:410} INFO - Running <TaskInstance: Mongodb_backup.test_ssh_operator scheduled__2023-05-11T04:20:00+00:00 [running]> on host b06a232a05e5
[2023-05-11T04:33:09.195+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Mongodb_backup' AIRFLOW_CTX_TASK_ID='test_ssh_operator' AIRFLOW_CTX_EXECUTION_DATE='2023-05-11T04:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-11T04:20:00+00:00'
[2023-05-11T04:33:09.197+0000] {ssh.py:135} INFO - Creating ssh_client
[2023-05-11T04:33:09.225+0000] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2023-05-11T04:33:09.237+0000] {base.py:73} INFO - Using connection ID 'ssh_conn' for task execution.
[2023-05-11T04:33:09.303+0000] {ssh.py:299} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-05-11T04:33:10.347+0000] {transport.py:1873} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2023-05-11T04:33:11.917+0000] {transport.py:1873} INFO - Authentication (publickey) successful!
[2023-05-11T04:33:11.921+0000] {ssh.py:476} INFO - Running command: 
echo 'Running shell script'
whoami
sh /home/ubuntu/dbbackup.sh
[2023-05-11T04:33:12.694+0000] {ssh.py:522} INFO - Running shell script
[2023-05-11T04:33:12.697+0000] {ssh.py:527} WARNING - /home/ubuntu/dbbackup.sh: 6: mongodump: not found
[2023-05-11T04:33:12.698+0000] {ssh.py:522} INFO - ubuntu
[2023-05-11T04:33:12.699+0000] {ssh.py:522} INFO - total 4.0K
[2023-05-11T04:33:12.700+0000] {ssh.py:522} INFO - -rw-r--r-- 1 ubuntu ubuntu 166 May 11 04:07 dbbackup.sh
[2023-05-11T04:33:12.704+0000] {ssh.py:522} INFO - total 4.0K
[2023-05-11T04:33:12.707+0000] {ssh.py:522} INFO - -rw-r--r-- 1 ubuntu ubuntu 166 May 11 04:07 dbbackup.sh
[2023-05-11T04:33:12.759+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=Mongodb_backup, task_id=test_ssh_operator, execution_date=20230511T042000, start_date=20230511T043309, end_date=20230511T043312
[2023-05-11T04:33:12.811+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-11T04:33:12.839+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
