[2023-05-11T05:28:56.204+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mongodb_backup.scp_to_server manual__2023-05-11T05:00:24.739667+00:00 [queued]>
[2023-05-11T05:28:56.224+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mongodb_backup.scp_to_server manual__2023-05-11T05:00:24.739667+00:00 [queued]>
[2023-05-11T05:28:56.225+0000] {taskinstance.py:1331} INFO - Starting attempt 10 of 11
[2023-05-11T05:28:56.247+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): scp_to_server> on 2023-05-11 05:00:24.739667+00:00
[2023-05-11T05:28:56.256+0000] {standard_task_runner.py:57} INFO - Started process 2158 to run task
[2023-05-11T05:28:56.264+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Mongodb_backup', 'scp_to_server', 'manual__2023-05-11T05:00:24.739667+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/dagforbackup.py', '--cfg-path', '/tmp/tmpr82jz4zh']
[2023-05-11T05:28:56.265+0000] {standard_task_runner.py:85} INFO - Job 148: Subtask scp_to_server
[2023-05-11T05:28:56.364+0000] {task_command.py:410} INFO - Running <TaskInstance: Mongodb_backup.scp_to_server manual__2023-05-11T05:00:24.739667+00:00 [running]> on host b06a232a05e5
[2023-05-11T05:28:56.511+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Mongodb_backup' AIRFLOW_CTX_TASK_ID='scp_to_server' AIRFLOW_CTX_EXECUTION_DATE='2023-05-11T05:00:24.739667+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-11T05:00:24.739667+00:00'
[2023-05-11T05:28:56.514+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-11T05:28:56.516+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', ' \nscp -i 3-mar-2023-N.Virginia.pem /Users/archanakarpe/Documents/saraff/MongoConnectionDags/dags/dbbackup.sh ubuntu@107.23.137.161:/home/ubuntu']
[2023-05-11T05:28:56.542+0000] {subprocess.py:86} INFO - Output:
[2023-05-11T05:28:56.567+0000] {subprocess.py:93} INFO - Warning: Identity file 3-mar-2023-N.Virginia.pem not accessible: No such file or directory.
[2023-05-11T05:28:57.719+0000] {subprocess.py:93} INFO - Host key verification failed.
[2023-05-11T05:28:57.723+0000] {subprocess.py:93} INFO - lost connection
[2023-05-11T05:28:57.727+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-11T05:28:57.763+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-11T05:28:57.770+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Mongodb_backup, task_id=scp_to_server, execution_date=20230511T050024, start_date=20230511T052856, end_date=20230511T052857
[2023-05-11T05:28:57.785+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 148 for task scp_to_server (Bash command failed. The command returned a non-zero exit code 1.; 2158)
[2023-05-11T05:28:57.823+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-11T05:28:57.869+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
