[2023-05-10T02:30:30.788+0000] {processor.py:156} INFO - Started process (PID=12075) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
[2023-05-10T02:30:30.872+0000] {processor.py:799} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py for tasks to queue
[2023-05-10T02:30:30.901+0000] {logging_mixin.py:149} INFO - [2023-05-10T02:30:30.900+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
[2023-05-10T04:05:44.907+0000] {processor.py:156} INFO - Started process (PID=12198) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
[2023-05-10T04:05:44.925+0000] {processor.py:799} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py for tasks to queue
[2023-05-10T04:05:44.954+0000] {logging_mixin.py:149} INFO - [2023-05-10T04:05:44.952+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
[2023-05-10T04:06:20.072+0000] {logging_mixin.py:149} INFO - [2023-05-10T04:06:20.005+0000] {timeout.py:68} ERROR - Process timed out, PID: 12198
[2023-05-10T04:06:20.077+0000] {logging_mixin.py:149} WARNING - Exception ignored in: <function WeakValueDictionary.__init__.<locals>.remove at 0xffff86ecb8c0>
[2023-05-10T04:06:20.084+0000] {logging_mixin.py:149} WARNING - Traceback (most recent call last):
[2023-05-10T04:06:20.116+0000] {logging_mixin.py:149} WARNING -   File "/usr/local/lib/python3.7/weakref.py", line 109, in remove
[2023-05-10T04:06:20.124+0000] {logging_mixin.py:149} WARNING -     def remove(wr, selfref=ref(self), _atomic_removal=_remove_dead_weakref):
[2023-05-10T04:06:20.132+0000] {logging_mixin.py:149} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
[2023-05-10T04:06:20.143+0000] {logging_mixin.py:149} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2023-05-10T04:06:20.158+0000] {logging_mixin.py:149} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.6.0/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.6.0/best-practices.html#reducing-dag-complexity, PID: 12198
[2023-05-10T04:06:26.013+0000] {processor.py:809} INFO - DAG(s) dict_keys(['example_kubernetes_executor']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
[2023-05-10T04:06:27.689+0000] {logging_mixin.py:149} INFO - [2023-05-10T04:06:27.683+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-05-10T04:06:29.028+0000] {logging_mixin.py:149} INFO - [2023-05-10T04:06:29.024+0000] {dag.py:3490} INFO - Setting next_dagrun for example_kubernetes_executor to None, run_after=None
[2023-05-10T04:06:29.303+0000] {processor.py:178} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py took 44.608 seconds
[2023-05-10T04:08:16.722+0000] {processor.py:156} INFO - Started process (PID=12284) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
[2023-05-10T04:08:16.735+0000] {processor.py:799} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py for tasks to queue
[2023-05-10T04:08:16.751+0000] {logging_mixin.py:149} INFO - [2023-05-10T04:08:16.750+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
[2023-05-10T04:08:47.222+0000] {logging_mixin.py:149} INFO - [2023-05-10T04:08:47.003+0000] {timeout.py:68} ERROR - Process timed out, PID: 12284
[2023-05-10T04:08:47.907+0000] {logging_mixin.py:149} INFO - [2023-05-10T04:08:47.436+0000] {dagbag.py:350} ERROR - Failed to import: /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py", line 39, in <module>
    from kubernetes.client import models as k8s
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/__init__.py", line 19, in <module>
    import kubernetes.client
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/__init__.py", line 20, in <module>
    from kubernetes.client.api.well_known_api import WellKnownApi
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/api/__init__.py", line 6, in <module>
    from kubernetes.client.api.well_known_api import WellKnownApi
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/api/well_known_api.py", line 20, in <module>
    from kubernetes.client.api_client import ApiClient
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/api_client.py", line 28, in <module>
    import kubernetes.client.models
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/models/__init__.py", line 382, in <module>
    from kubernetes.client.models.v1_toleration import V1Toleration
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.6.0/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.6.0/best-practices.html#reducing-dag-complexity, PID: 12284
[2023-05-10T04:08:49.042+0000] {processor.py:811} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
[2023-05-10T04:08:52.153+0000] {processor.py:178} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py took 35.520 seconds
[2023-05-10T04:13:57.993+0000] {processor.py:156} INFO - Started process (PID=12418) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
[2023-05-10T04:13:58.012+0000] {processor.py:799} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py for tasks to queue
[2023-05-10T04:13:58.036+0000] {logging_mixin.py:149} INFO - [2023-05-10T04:13:58.034+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
[2023-05-10T04:14:16.757+0000] {processor.py:809} INFO - DAG(s) dict_keys(['example_kubernetes_executor']) retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
[2023-05-10T04:14:19.601+0000] {logging_mixin.py:149} INFO - [2023-05-10T04:14:19.600+0000] {dag.py:2726} INFO - Sync 1 DAGs
[2023-05-10T04:14:20.168+0000] {logging_mixin.py:149} INFO - [2023-05-10T04:14:20.166+0000] {dag.py:3490} INFO - Setting next_dagrun for example_kubernetes_executor to None, run_after=None
[2023-05-10T04:14:20.807+0000] {processor.py:178} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py took 22.886 seconds
[2023-05-10T04:15:21.461+0000] {processor.py:156} INFO - Started process (PID=12474) to work on /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
[2023-05-10T04:15:21.501+0000] {processor.py:799} INFO - Processing file /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py for tasks to queue
[2023-05-10T04:15:21.518+0000] {logging_mixin.py:149} INFO - [2023-05-10T04:15:21.517+0000] {dagbag.py:541} INFO - Filling up the DagBag from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
[2023-05-10T04:15:51.751+0000] {logging_mixin.py:149} INFO - [2023-05-10T04:15:51.690+0000] {timeout.py:68} ERROR - Process timed out, PID: 12474
[2023-05-10T04:15:52.276+0000] {logging_mixin.py:149} INFO - [2023-05-10T04:15:51.853+0000] {dagbag.py:350} ERROR - Failed to import: /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py", line 39, in <module>
    from kubernetes.client import models as k8s
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/__init__.py", line 19, in <module>
    import kubernetes.client
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/__init__.py", line 20, in <module>
    from kubernetes.client.api.well_known_api import WellKnownApi
  File "/home/airflow/.local/lib/python3.7/site-packages/kubernetes/client/api/__init__.py", line 57, in <module>
    from kubernetes.client.api.rbac_authorization_api import RbacAuthorizationApi
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 828, in get_code
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 69, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.6.0/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.6.0/best-practices.html#reducing-dag-complexity, PID: 12474
[2023-05-10T04:15:52.432+0000] {processor.py:811} WARNING - No viable dags retrieved from /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py
[2023-05-10T04:15:54.001+0000] {processor.py:178} INFO - Processing /home/airflow/.local/lib/python3.7/site-packages/airflow/example_dags/example_kubernetes_executor.py took 32.662 seconds
