[2023-05-10T04:55:06.496+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_stuff.run_remote_script scheduled__2023-05-10T04:30:00+00:00 [queued]>
[2023-05-10T04:55:06.514+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_stuff.run_remote_script scheduled__2023-05-10T04:30:00+00:00 [queued]>
[2023-05-10T04:55:06.515+0000] {taskinstance.py:1331} INFO - Starting attempt 6 of 7
[2023-05-10T04:55:06.538+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): run_remote_script> on 2023-05-10 04:30:00+00:00
[2023-05-10T04:55:06.549+0000] {standard_task_runner.py:57} INFO - Started process 772 to run task
[2023-05-10T04:55:06.559+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'testing_stuff', 'run_remote_script', 'scheduled__2023-05-10T04:30:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmp7a3gxn7j']
[2023-05-10T04:55:06.561+0000] {standard_task_runner.py:85} INFO - Job 45: Subtask run_remote_script
[2023-05-10T04:55:06.680+0000] {task_command.py:410} INFO - Running <TaskInstance: testing_stuff.run_remote_script scheduled__2023-05-10T04:30:00+00:00 [running]> on host 448394b5800f
[2023-05-10T04:55:06.814+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='testing_stuff' AIRFLOW_CTX_TASK_ID='run_remote_script' AIRFLOW_CTX_EXECUTION_DATE='2023-05-10T04:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-10T04:30:00+00:00'
[2023-05-10T04:55:06.817+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-10T04:55:06.819+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '#!/bin/bash\n\nls -lthr\npwd\ncat test']
[2023-05-10T04:55:06.837+0000] {subprocess.py:86} INFO - Output:
[2023-05-10T04:55:06.854+0000] {subprocess.py:93} INFO - total 0
[2023-05-10T04:55:06.856+0000] {subprocess.py:93} INFO - /tmp/***tmpaoyp__jv
[2023-05-10T04:55:06.860+0000] {subprocess.py:93} INFO - cat: test: No such file or directory
[2023-05-10T04:55:06.861+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-05-10T04:55:06.887+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-05-10T04:55:06.895+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=testing_stuff, task_id=run_remote_script, execution_date=20230510T043000, start_date=20230510T045506, end_date=20230510T045506
[2023-05-10T04:55:06.911+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 45 for task run_remote_script (Bash command failed. The command returned a non-zero exit code 1.; 772)
[2023-05-10T04:55:06.934+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-10T04:55:06.958+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
