[2023-05-10T05:18:06.278+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: testing_stuff.run_remote_script scheduled__2023-05-10T05:00:00+00:00 [queued]>
[2023-05-10T05:18:06.287+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: testing_stuff.run_remote_script scheduled__2023-05-10T05:00:00+00:00 [queued]>
[2023-05-10T05:18:06.288+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 3
[2023-05-10T05:18:06.300+0000] {taskinstance.py:1350} INFO - Executing <Task(BashOperator): run_remote_script> on 2023-05-10 05:00:00+00:00
[2023-05-10T05:18:06.305+0000] {standard_task_runner.py:57} INFO - Started process 1199 to run task
[2023-05-10T05:18:06.312+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'testing_stuff', 'run_remote_script', 'scheduled__2023-05-10T05:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpfz2yrxzz']
[2023-05-10T05:18:06.313+0000] {standard_task_runner.py:85} INFO - Job 56: Subtask run_remote_script
[2023-05-10T05:18:06.398+0000] {task_command.py:410} INFO - Running <TaskInstance: testing_stuff.run_remote_script scheduled__2023-05-10T05:00:00+00:00 [running]> on host 448394b5800f
[2023-05-10T05:18:06.498+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='testing_stuff' AIRFLOW_CTX_TASK_ID='run_remote_script' AIRFLOW_CTX_EXECUTION_DATE='2023-05-10T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-10T05:00:00+00:00'
[2023-05-10T05:18:06.500+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-05-10T05:18:06.502+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '#!/bin/bash\n\n#Backup Data from control.brandsonroad.com\ncd ~\nls -lthr\nmongodump --forceTableScan --db led --gzip --archive=mongoBackup_$(date +"%Y-%m-%d.gz")\nls -lthr']
[2023-05-10T05:18:06.514+0000] {subprocess.py:86} INFO - Output:
[2023-05-10T05:18:06.525+0000] {subprocess.py:93} INFO - total 0
[2023-05-10T05:18:06.533+0000] {subprocess.py:93} INFO - /bin/bash: line 6: mongodump: command not found
[2023-05-10T05:18:06.537+0000] {subprocess.py:93} INFO - total 0
[2023-05-10T05:18:06.537+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-05-10T05:18:06.575+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=testing_stuff, task_id=run_remote_script, execution_date=20230510T050000, start_date=20230510T051806, end_date=20230510T051806
[2023-05-10T05:18:06.606+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-10T05:18:06.627+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
