[2023-05-11T06:20:29.442+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Mongodb_backup.run_script scheduled__2023-05-11T05:00:00+00:00 [queued]>
[2023-05-11T06:20:29.452+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Mongodb_backup.run_script scheduled__2023-05-11T05:00:00+00:00 [queued]>
[2023-05-11T06:20:29.453+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-05-11T06:20:29.468+0000] {taskinstance.py:1350} INFO - Executing <Task(SSHOperator): run_script> on 2023-05-11 05:00:00+00:00
[2023-05-11T06:20:29.476+0000] {standard_task_runner.py:57} INFO - Started process 3345 to run task
[2023-05-11T06:20:29.485+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Mongodb_backup', 'run_script', 'scheduled__2023-05-11T05:00:00+00:00', '--job-id', '205', '--raw', '--subdir', 'DAGS_FOLDER/dagforbackup.py', '--cfg-path', '/tmp/tmpthwue4r6']
[2023-05-11T06:20:29.486+0000] {standard_task_runner.py:85} INFO - Job 205: Subtask run_script
[2023-05-11T06:20:29.550+0000] {task_command.py:410} INFO - Running <TaskInstance: Mongodb_backup.run_script scheduled__2023-05-11T05:00:00+00:00 [running]> on host b06a232a05e5
[2023-05-11T06:20:29.648+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='***@example.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Mongodb_backup' AIRFLOW_CTX_TASK_ID='run_script' AIRFLOW_CTX_EXECUTION_DATE='2023-05-11T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-05-11T05:00:00+00:00'
[2023-05-11T06:20:29.650+0000] {ssh.py:135} INFO - Creating ssh_client
[2023-05-11T06:20:29.696+0000] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2023-05-11T06:20:29.708+0000] {base.py:73} INFO - Using connection ID 'ssh_conn' for task execution.
[2023-05-11T06:20:29.775+0000] {ssh.py:299} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-05-11T06:20:30.329+0000] {transport.py:1873} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2023-05-11T06:20:31.536+0000] {transport.py:1873} INFO - Authentication (publickey) successful!
[2023-05-11T06:20:31.540+0000] {ssh.py:476} INFO - Running command: 
echo 'Running shell script'
whoami
sh -x /home/ubuntu/dbbackup.sh
[2023-05-11T06:20:32.357+0000] {ssh.py:522} INFO - Running shell script
[2023-05-11T06:20:32.362+0000] {ssh.py:522} INFO - ubuntu
[2023-05-11T06:20:32.363+0000] {ssh.py:527} WARNING - + cd /home/ubuntu
[2023-05-11T06:20:32.364+0000] {ssh.py:527} WARNING - + ls -lthr
[2023-05-11T06:20:32.365+0000] {ssh.py:527} WARNING - + date +%Y-%m-%d.gz
[2023-05-11T06:20:32.367+0000] {ssh.py:527} WARNING - + mongodump --forceTableScan --db led --gzip --archive=mongoBackup_2023-05-11.gz
[2023-05-11T06:20:32.368+0000] {ssh.py:527} WARNING - /home/ubuntu/dbbackup.sh: 6: mongodump: not found
[2023-05-11T06:20:32.368+0000] {ssh.py:527} WARNING - + ls -lthr
[2023-05-11T06:20:32.370+0000] {ssh.py:522} INFO - total 4.0K
[2023-05-11T06:20:32.371+0000] {ssh.py:522} INFO - -rw-r--r-- 1 ubuntu ubuntu 166 May 11 06:20 dbbackup.sh
[2023-05-11T06:20:32.373+0000] {ssh.py:522} INFO - total 4.0K
[2023-05-11T06:20:32.374+0000] {ssh.py:522} INFO - -rw-r--r-- 1 ubuntu ubuntu 166 May 11 06:20 dbbackup.sh
[2023-05-11T06:20:32.705+0000] {taskinstance.py:1373} INFO - Marking task as SUCCESS. dag_id=Mongodb_backup, task_id=run_script, execution_date=20230511T050000, start_date=20230511T062029, end_date=20230511T062032
[2023-05-11T06:20:32.801+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 0
[2023-05-11T06:20:32.867+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
